
services:
  web:
    container_name: react-course-admin_web
    restart: unless-stopped
    env_file: ./web/.env
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 8011:80

  server:
    container_name: react-course-admin_server
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8111:3001
