version: "3"
services:
  frontend:
    container_name: course-admin_web
    build:
      context: ./web
      dockerfile: Dockerfile
    image: course-admin_web
    ports:
      - "8011:80"
  backend:
    container_name: course-admin_server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: node:lts-slim
    ports:
      - "8111:3001"
    volumes:
      - ./server:/usr/src/app
