
services:
  web:
    container_name: react-course-admin_web
    environment:
      ENV: ${ENV}
    image: incerto13/react-course-admin_web:${ENV}-latest
    restart: unless-stopped
    env_file: ./web/.env
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 8011:80

  server:
    container_name: react-course-admin_server
    environment:
      ENV: ${ENV}
    image: incerto13/react-course-admin_server:${ENV}-latest
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8111:3001
