# build images during github workflow that pushes (w/ tags) to docker hub
# should only need to push images for postgres, server and web

services:

  react-to-do_postgres:
    image: incerto13/react-to-do_postgres:${ENV}-latest
    container_name: react-to-do_postgres
    build:
      context: ./server
      dockerfile: ./docker/postgres/Dockerfile   

  react-course-admin_server:
    image: incerto13/react-course-admin_server:${ENV}-latest
    container_name: react-course-admin_server
    build:
      context: ./server
      dockerfile: Dockerfile

  react-course-admin_web:
    image: incerto13/react-course-admin_web:${ENV}-latest
    container_name: react-course-admin_web
    env_file: ./web/.env
    build:
      context: ./web
      dockerfile: ./docker/Dockerfile