version: "3"
services:
  frontend:
    container_name: course-admin_web
    restart: unless-stopped
    env_file: ./web/.env
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8011:80"
    links:
      - backend
  backend:
    container_name: course-admin_server
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8111:3001"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
